spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
