spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource:
    url: ${MySQL_HOST_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MySQL_USERNAME}
    password: ${MySQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
